use_frameworks!

platform :ios, '10.0'

target 'ZLTagListView_Example' do
  pod 'ZLTagListView', :path => '../'
  pod 'ZLPopView', :path => '../../ZLPopView'

  target 'ZLTagListView_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
